intercom/Intercom-OpenAPI

descriptions/api.intercom.io.yaml
This PR adds support for Open API specification for [Segments API ](https://developers.intercom.com/intercom-api-reference/reference/the-segment-model)
=> Add specification for Segments API

scripts/postman/collection.js
Adding try catch around tag fetching to prevent deployment failures.
[Deployment](https://github.com/intercom/Intercom-OpenAPI/actions/runs/4295667329/attempts/1) failed because  the Tag is [Ticket Type Attributes](https://github.com/intercom/intercom/blob/2930500569964f4f9556597187c694948e43fc51/app/lib/api/open_api/tags/ticket_type_attributes.rb#L8) but the spec is tagged as [TicketTypeAttributes](https://github.com/intercom/intercom/blob/aa4a2a553669314fe366e84c7c5f9e19d53b1ff2/spec/requests/api/v3/ticket_types/ticket_type_attributes_spec.rb#L7)  ( no spaces)
=> Adding try catch around tag fetching to prevent deployment failures

scripts/postman/collection.js
[Deployment](https://github.com/intercom/Intercom-OpenAPI/actions/runs/4438375783/jobs/7789338021) of changes https://github.com/intercom/Intercom-OpenAPI/pull/64 to postman collection has failed. 
It failed because we couldn't find a 'tag' to place the endpoint into. 
This PR updates the catch to correctly handle this.
=> Fixing no endpoint tag issue

descriptions/0/api.intercom.io.yaml, descriptions/2.10/api.intercom.io.yaml, descriptions/2.7/api.intercom.io.yaml, descriptions/2.8/api.intercom.io.yaml, descriptions/2.9/api.intercom.io.yaml
toward [318937](https://github.com/intercom/intercom/issues/318937) & [325446](https://github.com/intercom/intercom/pull/325446)
- Adds `attachment_files` to conversation replies because it is [available in the API](https://github.com/intercom/intercom/blob/master/app/controllers/api/v3/conversations_controller.rb#L821-L837) but missing from the docs
- Fix the broken id option in the path param
- Update some formatting leftover from README
=> Add attachment files to conversation reply 

descriptions/0/api.intercom.io.yaml
Adding schemas to Unstable
- email message metadata
- email address header
Updated conversation part schema to include email message metadata
```
email_address_header:
title: Email Address Header
type: object
description: Contains data for an email address header for a conversation part
that was sent as an email.
properties:
type:
type: string
description: The type of email address header
example: from
email_address:
type: string
description: The email address
example: wash@serenity.io
name:
type: string
nullable: true
description: The name associated with the email address
example: Hoban Washburne
email_message_metadata:
title: Email Message Metadata
type: object
description: Contains metadata if the message was sent as an email
properties:
subject:
type: string
description: The subject …
```
=> Update Unstable spec with email metadata schemas

descriptions/2.11/api.intercom.io.yaml, fern/fern.config.json
The `contact`, `article` and `admin` resources were missing required properties. This PR adds them to the objects so that the generated SDKs are more ergonomic.
=> feat: add `required` to 2.11 OpenAPI objects

descriptions/2.11/api.intercom.io.yaml
- Move `nullable: true` from schemas to schema references
- Don't add `nullable: true` to request bodies
=> Update nullables in spec to be on references, not on schemas

descriptions/0/api.intercom.io.yaml
https://github.com/intercom/intercom/issues/382977
Why?
Add block user endpoint to unstable open_api.yml
> not to get confused by the Intercom-Version - Available values which contains all the versions
> those are acceptable values for this filed, and the contacts/:id/block endpoint is only available on Unstable version
Actual implementation: https://github.com/intercom/intercom/pull/384449
=> add block contact API to unstable version

REPO_OWNER, descriptions/0/api.intercom.io.yaml
Towards: https://github.com/intercom/intercom/issues/379548
- Update repo owner based on new remits
- Update unstable yaml to include new response fields in the docs
=> Add new conversation API fields to the developer docs & changelog

descriptions/0/api.intercom.io.yaml
https://github.com/intercom/intercom/issues/382977
I think the problem might be the extra `:` in the description (from https://github.com/intercom/Intercom-OpenAPI/pull/202)
=> update block contact description

descriptions/0/api.intercom.io.yaml, descriptions/2.11/api.intercom.io.yaml, descriptions/2.12/api.intercom.io.yaml
Closes https://github.com/intercom/intercom/issues/386886
Related to escalation request: https://app.intercom.com/a/apps/tx2p130c/conversations/40658072881
This functionality has been available since version 2.11 of the API when it was added in this PR https://github.com/intercom/intercom/pull/302855 to enable it for ticket migrations from Zendesk. However, it was never documented publicly.
=> Add created_at field to create conversation request body for v2.11+

descriptions/0/api.intercom.io.yaml
Adding documentation for changes made in https://github.com/intercom/intercom/pull/385143
Adding support for sms message type to the Messages endpoint
#How?
This pull request updates the API documentation to include support for SMS messages in addition to the existing in-app and email message types. The most important changes include updates to the message creation endpoint, error handling, and schema definitions.
* [`descriptions/0/api.intercom.io.yaml`](diffhunk://#diff-0fc8ffce3e89e8d8c5d9aec75e14df5bd507ab1f03a49fabbe42945953229f25L8480-R8480): Added SMS as a valid message type in the `createMessage` operation description.
* [`descriptions/0/api.intercom.io.yaml`](diffhunk://#diff-0fc8ffce3e89e8d8c5d9aec75e14df5bd507ab1f03a49fabbe42945953229f25R8546-R8552): Added error handling for …
=> Updating Messages documentation

.gitignore, descriptions/0/api.intercom.io.yaml
Follow up to https://github.com/intercom/intercom/pull/387414
Adding the spec for the new title param in the update conversation endpoint in Conversation API
(also expanding the gitignore for rubymine users 😬)
=> add title param in update conversation endpoint spec

descriptions/0/api.intercom.io.yaml
Added `app_package_code` to `conversation_part` and `ticket_part` in the unstable version doc
=> add package_package_code to conversation_part and ticket_part

descriptions/0/api.intercom.io.yaml
Follow up https://github.com/intercom/intercom/pull/394442
=> Update ticket request schema (unstable)

descriptions/0/api.intercom.io.yaml
Follow up: [Updating endpoint - set admin as away](https://github.com/intercom/intercom/issues/393911)
=> add away_status_reason_id to admins away endpoint

descriptions/0/api.intercom.io.yaml
Adds updates from the following additions to unstable:
https://github.com/intercom/intercom/pull/397939
https://github.com/intercom/intercom/pull/391366
https://github.com/intercom/intercom/pull/397239
=> Add quick reply documentation and AI agent author fields

descriptions/2.13/api.intercom.io.yaml
Thank you for contributing to [intercom/Intercom-OpenAPI](https://github.com/intercom/Intercom-OpenAPI)!
=> added docs to internal articles api

descriptions/0/api.intercom.io.yaml
Updating openAPI spec for unstable based on recent changes in
https://github.com/intercom/intercom/pull/382065/files
and
https://github.com/intercom/intercom/pull/398240#pullrequestreview-2809525999
Essentially just enable multiple recipients now and a new bcc field
=> Adding To, CC and BCC info to docs

descriptions/0/api.intercom.io.yaml
API PRs:
- https://github.com/intercom/intercom/pull/398844
- https://github.com/intercom/intercom/pull/401996
Developer docs PR: https://github.com/intercom/developer-docs/pull/549
Loom:
https://www.loom.com/share/35ff47d0e7ec4c9ebf40c9ed036a65a5?sid=91b13b1a-8545-47b4-a8a8-1c13963b5e32
=> add public documentation for WA outbound metrics api

descriptions/0/api.intercom.io.yaml, fern/openapi-overrides.yml
Add documentation for the new API endpoints for Custom Channel Events, that are used on a closed beta to allow "Fin over API" types of integration.
The changes were tested using a Swagger editor:
https://github.com/user-attachments/assets/67595e4b-ac85-4f6e-94a2-74faf4e7ec97
=> Add Custom Channel Event endpoints documentation

.github/workflows/ts-sdk.yml, scripts/fern/bump.sh
- Added a script (`bump.sh`) that determines the correct version number to set when we re-deploy the SDK
- Updated `ts-sdk.yml` to automatically re-deploy the TS SDK when PRs get merged to the `fern` folder within this repo
- Calls `bump.sh` to get the correct version # when we auto re-deploy the SDK
- I'll implement this for the Java SDK once we start publishing to Maven
=> Automatically re-generate the TS SDK when we merge PRs to this repo

descriptions/0/api.intercom.io.yaml
The aim of this PR is to add API docs related to reporting data-export.
We are documenting below requests handled by `app/controllers/api/v3/export/reporting_data_export_controller.rb` controller.
- `POST /export/reporting_data/enqueue`
- `GET /export/reporting_data/{job_identifier}`
- `GET /download/reporting_data/{job_identifier}`
- `GET /export/reporting_data/get_datasets`
=> Add docs related to reporting data export

descriptions/0/api.intercom.io.yaml
We have added a new filed to `Ticket Part` to share the updated attribute data within the webhook response.
Towards https://github.com/intercom/intercom/pull/407086
=> Update OpenAPI spec for ticket updated attribute metadata

descriptions/0/api.intercom.io.yaml
Attributes "email" and "name" should only be required for users and not for leads.
=> Update custom_channel_contact schema

descriptions/0/api.intercom.io.yaml
Adding the docs for the Whatsapp outbound API messages
=> Create docs for Whatsapp API messages

descriptions/0/api.intercom.io.yaml
It is not a beta but rather under managed availability.
=> Update Fin over API availability documentation

descriptions/0/api.intercom.io.yaml, descriptions/2.10/api.intercom.io.yaml, descriptions/2.11/api.intercom.io.yaml, descriptions/2.12/api.intercom.io.yaml, descriptions/2.13/api.intercom.io.yaml, descriptions/2.14/api.intercom.io.yaml, descriptions/2.7/api.intercom.io.yaml, descriptions/2.8/api.intercom.io.yaml, descriptions/2.9/api.intercom.io.yaml
- Doing this as a part of https://github.com/intercom/intercom/issues/421822
- PR: https://github.com/intercom/intercom/pull/418380
Added url_prefix field to help_center schema for URL path prefix 
Added custom_domain field to help_center schema for custom domain configuration (nullable)
Updated all API versions (0, 2.7-2.14) since Help Center endpoints are not version-gated
=> Help center OpenAPI update

descriptions/0/api.intercom.io.yaml, descriptions/2.10/api.intercom.io.yaml, descriptions/2.11/api.intercom.io.yaml, descriptions/2.12/api.intercom.io.yaml, descriptions/2.13/api.intercom.io.yaml, descriptions/2.14/api.intercom.io.yaml, descriptions/2.7/api.intercom.io.yaml, descriptions/2.8/api.intercom.io.yaml, descriptions/2.9/api.intercom.io.yaml
- https://github.com/intercom/intercom/issues/421822
- Renamed `url_prefix` field to `url` to better reflect that it contains the full URL
- Improved url description ( added a sentence for custom domain behavior
- Fixed brand tag ordering and improved brand documentation
=> Rename url_prefix field to url in help center API response

descriptions/2.14/api.intercom.io.yaml
2.14 introduced some breaking changes around id names which also cause confusion in the endpoints bc they are non-specific
=> Fixing the IDs

descriptions/0/api.intercom.io.yaml, descriptions/2.14/api.intercom.io.yaml, fern/openapi-overrides.yml, postman/2.14/intercom-api.postman_collection.json, postman/Unstable/intercom-api.postman_collection.json
- Update description for the "/download/reporting_data/{job_identifier}" endpoint, specifying the requirement for the Accept header with value `application/octet-stream`.
- Updated parameter definitions to include the Accept header as a required field for downloading export files.
=> Enhance API documentation for export job data download
