intercom/Intercom-OpenAPI

descriptions/api.intercom.io.yaml

Adding Open API spec for Data Events endpoint(Unstable).

Adding Open API spec for Data Events endpoint

---

descriptions/api.intercom.io.yaml

Adding Open API spec for Articles endpoint(Unstable).

Adding Open API spec for Articles and Tags endpoints

---

descriptions/api.intercom.io.yaml

Update open API spec with latest changes from intercom master

Update yaml file with latest changes from intercom master

---

scripts/create-new-spec.js
scripts/delete-spec.js
scripts/get-spec-version.js
scripts/update-existing-spec.js
scripts/upload-api-specification.js

towards  https://github.com/intercom/intercom/issues/268470

Adding retry logic to Openapi create upload script

---

scripts/create-new-spec.js
scripts/update-existing-spec.js

towards  https://github.com/intercom/intercom/issues/268470

Refactoring retrylogic to update call

---

scripts/upload-api-specification.js

Updating parameters for CreateNewSpec

Updating createNewSpec parameters

---

descriptions/0/api.intercom.io.yaml

Updating api.intercom.io.yaml

---

descriptions/2.7/api.intercom.io.yaml
descriptions/2.8/api.intercom.io.yaml

Adding 2.7 and 2.8 spec changes

adding 2.7 and 2.8 spec changes

---

scripts/update-existing-spec.js

Increasing wait between upload attempts in an attempt to resolve  `-1` slug issue
https://github.com/intercom/intercom/issues/271281

Increasing wait between upload attempts

---

descriptions/0/api.intercom.io.yaml
descriptions/2.7/api.intercom.io.yaml
descriptions/2.8/api.intercom.io.yaml

Updating OpenAPI yaml docs

---

.github/workflows/generate_postman_collection.yml
package-lock.json
package.json
scripts/postman/create-collection-from-yaml.js
scripts/postman/create-postman-collection.js
scripts/postman/run-postman-collection.js
scripts/postman/update-postman-collection.js
scripts/postman/upload-collections-to-postman.js
scripts/utils/API_KEYS.js

Adding scripts to generate a postman collection from our Intercom OpanApi files and upload it to Postman
closes https://github.com/intercom/intercom/issues/268468

Adding scripts to generate postman collection and upload it

---

.github/workflows/generate_postman_collection.yml

Fixing script command path

---

descriptions/0/api.intercom.io.yaml
descriptions/2.7/api.intercom.io.yaml
descriptions/2.8/api.intercom.io.yaml

Updating openapi docs

---

.gitignore
scripts/postman/collection.js
scripts/postman/create-collection-from-yaml.js
scripts/postman/example.js
scripts/postman/open-api.js

Improved api to postman conversion

Improved api to postman conversion

---

descriptions/0/api.intercom.io.yaml
descriptions/2.7/api.intercom.io.yaml
descriptions/2.8/api.intercom.io.yaml

Creating PR to release postman collection

Creating PR to release postman collection

---

.github/workflows/generate_postman_collection.yml
scripts/postman/create-postman-collection.js
scripts/postman/upload-collections-to-postman.js
scripts/utils/API_KEYS.js

Adding support for Workspace IDs to ensure correct postman collection is updated

Adding workspace id

---

descriptions/0/api.intercom.io.yaml
descriptions/2.7/api.intercom.io.yaml
descriptions/2.8/api.intercom.io.yaml

Updating docs to trigger postman gha

Updating docs to trigger gha

---

descriptions/0/api.intercom.io.yaml
descriptions/2.7/api.intercom.io.yaml
descriptions/2.8/api.intercom.io.yaml

Adding more details to create export data api page in open api documentation.
Link to Intermission / issue
adding details of parameters and descriptions.

updaintg file - create export data api page

---

scripts/postman/create-collection-from-yaml.js

Fixing console.error log. Replacing collectionName with filePath

Replacing collectionName with filepath

---

descriptions/2.7/api.intercom.io.yaml
descriptions/2.8/api.intercom.io.yaml

PR: https://github.com/intercom/intercom/pull/272727
Schema changes:
- Update collection endpoints
- remove `type`
- add `parent_id`
- Add back section endpoints for <2.8

Update collection endpoints

---

descriptions/0/api.intercom.io.yaml
descriptions/2.7/api.intercom.io.yaml
descriptions/2.8/api.intercom.io.yaml

Attempt no 2 of https://github.com/intercom/Intercom-OpenAPI/pull/53 as I didn't copy paste the files correctly
PR: https://github.com/intercom/intercom/pull/272727
Schema changes:
- Update collection endpoints
- remove `type`
- add `parent_id`
- Add back section endpoints for <2.8

Update collection spec

---

descriptions/2.7/api.intercom.io.yaml
descriptions/2.8/api.intercom.io.yaml

related https://github.com/intercom/intercom/pull/273429

input options fix

---

descriptions/0/api.intercom.io.yaml
descriptions/2.7/api.intercom.io.yaml
descriptions/2.8/api.intercom.io.yaml

related https://github.com/intercom/intercom/pull/273593

Updating openapi docs to use sorted tags and schemas

---

descriptions/0/api.intercom.io.yaml

Copy the changes over from https://github.com/intercom/intercom/pull/274979

Publish new OpenAPI spec

---

descriptions/0/api.intercom.io.yaml

uploading the [changes to the openapi spec ](https://github.com/intercom/intercom/pull/275480)

Unstable update for adding ticket notes

---

descriptions/0/api.intercom.io.yaml

Copies over changes from https://github.com/intercom/intercom/pull/276269
Passes validation in the Swagger editor:

Release new OpenAPI spec

---

descriptions/0/api.intercom.io.yaml

Publishing changes from https://github.com/intercom/intercom/pull/277359
Validated no new errors shown by the swagger editor (conversation ones are there for a while now):

Publish OpenAPI spec

---

descriptions/0/api.intercom.io.yaml

Follow up to https://github.com/intercom/intercom/pull/280147 to regenerate openAPI spec.
Fixes https://github.com/intercom/intercom/issues/279477

Updating unstable spec

---

descriptions/0/api.intercom.io.yaml

Publishing changes from https://github.com/intercom/intercom/pull/284159

Publish the new OpenAPI spec

---

descriptions/2.9/api.intercom.io.yaml

Create a 2.9 open api yml file generated from the 2.9 release change

API 2.9 Open api spec

---

descriptions/2.9/api.intercom.io.yaml

Added version and pulled the latest OpenAPI spec with /notes renamed to /reply:

Fixes to 2.9 spec

---

descriptions/0/api.intercom.io.yaml

Updating Ticket search docs to include ticket attribute filter information
Closes https://github.com/intercom/intercom/issues/287616

Ticket Search attribute filter

---

descriptions/0/api.intercom.io.yaml

Fix spelling mistake in companies spec

---

descriptions/0/api.intercom.io.yaml

https://github.com/intercom/intercom/issues/291161

Ticket API V3 model changes

---

descriptions/0/api.intercom.io.yaml

https://intercom.slack.com/archives/C04A01XNTFU/p1690294391837319

Fix broken yml from ticket api changes

---

descriptions/0/api.intercom.io.yaml
descriptions/2.7/api.intercom.io.yaml
descriptions/2.8/api.intercom.io.yaml
descriptions/2.9/api.intercom.io.yaml

Live doc site changes from https://github.com/intercom/intercom/pull/297633

Multi HC Doc updates

---

descriptions/2.7/api.intercom.io.yaml
descriptions/2.8/api.intercom.io.yaml

updating 2.7 and 2.8 version of api spec
part of https://github.com/intercom/intercom/issues/297928

update 2.7 and 2.8 api version

---

descriptions/0/api.intercom.io.yaml

Updates OpenAPI spec to bring up to date with the version from https://github.com/intercom/intercom/pull/298483

Add AI Content APIs to API docs

---

descriptions/0/api.intercom.io.yaml
descriptions/2.9/api.intercom.io.yaml

Closes https://github.com/intercom/intercom/issues/297928

updating 2.9 and unstable docs

---

descriptions/0/api.intercom.io.yaml

Updating live doc site from https://github.com/intercom/intercom/pull/298948

Article/search update Unstable

---

.gitignore
descriptions/0/api.intercom.io.yaml
descriptions/2.7/api.intercom.io.yaml
descriptions/2.8/api.intercom.io.yaml
descriptions/2.9/api.intercom.io.yaml

- Add DS_Store to gitignore
- latest OAS

Update OAS to latest

---

descriptions/0/api.intercom.io.yaml

Following from https://github.com/intercom/intercom/pull/299654

Article/search - update path params to query params

---

descriptions/0/api.intercom.io.yaml
descriptions/2.10/api.intercom.io.yaml
descriptions/2.7/api.intercom.io.yaml
descriptions/2.8/api.intercom.io.yaml
descriptions/2.9/api.intercom.io.yaml

Update spec to fix a typo in the `visitors/<id>/convert` endpoint. The key should be `user` instead of `contact`.

Update visitor/convert endpoint

---

descriptions/0/api.intercom.io.yaml
descriptions/2.10/api.intercom.io.yaml
descriptions/2.7/api.intercom.io.yaml
descriptions/2.8/api.intercom.io.yaml
descriptions/2.9/api.intercom.io.yaml

Removing conversations attributes from create/update as the data attribute API does not support this

Update data attribute create/update endpoint

---

descriptions/0/api.intercom.io.yaml
descriptions/2.10/api.intercom.io.yaml
descriptions/2.7/api.intercom.io.yaml
descriptions/2.8/api.intercom.io.yaml
descriptions/2.9/api.intercom.io.yaml

- Remove `tag_id` and `segment_id` from List all Companies
- Add `tag_id` and `segment_id` to Get Companies
- Fix typos

Update parameters for List all Companies and Get Companies

---

descriptions/0/api.intercom.io.yaml
descriptions/2.10/api.intercom.io.yaml
descriptions/2.7/api.intercom.io.yaml
descriptions/2.8/api.intercom.io.yaml
descriptions/2.9/api.intercom.io.yaml

Follow up from https://github.com/intercom/intercom/pull/322240
This PR adds:
* New Custom Object Instances API to Unstable version
* New `messenger_writable` attribute to all api versions (https://github.com/intercom/intercom/issues/320879)

Add Custom Object Instances API & custom attribute messenger_writable

---

descriptions/0/api.intercom.io.yaml
descriptions/2.10/api.intercom.io.yaml
descriptions/2.7/api.intercom.io.yaml
descriptions/2.8/api.intercom.io.yaml
descriptions/2.9/api.intercom.io.yaml

fixes the `external_id` parameter and the two `GET` headlines for clarity

Updating Custom Objects Spec

---

descriptions/0/api.intercom.io.yaml
descriptions/2.10/api.intercom.io.yaml
descriptions/2.9/api.intercom.io.yaml

toward [#324375](https://github.com/intercom/intercom/pull/324375)
adds information around new Ticket States parameters in versions `2.9`, `2.10`, and `Unstable`

Adding Ticket States

---

descriptions/0/api.intercom.io.yaml
descriptions/2.10/api.intercom.io.yaml
descriptions/2.7/api.intercom.io.yaml
descriptions/2.8/api.intercom.io.yaml
descriptions/2.9/api.intercom.io.yaml

toward [325030](https://github.com/intercom/intercom/pull/325030)
provided fields should be on `source.type` not `channel_initiated`

Fix values on source.type field

---

descriptions/0/api.intercom.io.yaml
descriptions/2.10/api.intercom.io.yaml
descriptions/2.7/api.intercom.io.yaml
descriptions/2.8/api.intercom.io.yaml
descriptions/2.9/api.intercom.io.yaml

toward [311979](https://github.com/intercom/intercom/pull/311979) & [285869](https://github.com/intercom/intercom/issues/285869)
statistics removed from listed articles for performance reasons

Remove statistics

---

descriptions/0/api.intercom.io.yaml
descriptions/2.10/api.intercom.io.yaml
descriptions/2.7/api.intercom.io.yaml
descriptions/2.8/api.intercom.io.yaml
descriptions/2.9/api.intercom.io.yaml

towards https://github.com/intercom/intercom/pull/329732 mostly typos

Update docs errors

---

descriptions/0/api.intercom.io.yaml
descriptions/2.10/api.intercom.io.yaml
descriptions/2.7/api.intercom.io.yaml
descriptions/2.8/api.intercom.io.yaml
descriptions/2.9/api.intercom.io.yaml

toward [330296](https://github.com/intercom/intercom/pull/330296) and [330148](https://github.com/intercom/intercom/pull/330148)

Update maxItems on Conversations and Tickets objects

---

descriptions/0/api.intercom.io.yaml

toward [384](https://github.com/intercom/developer-docs/pull/384) and [330104](https://github.com/intercom/intercom/pull/330104)

Adding AI Chatbot Metadata updates

---

descriptions/0/api.intercom.io.yaml

Includes update from monolith PR https://github.com/intercom/intercom/pull/332701

AI Agent add enums to open_api content source content types

---

descriptions/0/api.intercom.io.yaml
descriptions/2.10/api.intercom.io.yaml
descriptions/2.11/api.intercom.io.yaml
descriptions/2.7/api.intercom.io.yaml
descriptions/2.8/api.intercom.io.yaml
descriptions/2.9/api.intercom.io.yaml

toward https://github.com/intercom/intercom/pull/334446 + https://github.com/intercom/intercom/issues/334445
Updates the docs and adds OpenAPI specs for v2.11

Adding API 2.11 

---

descriptions/0/api.intercom.io.yaml

toward https://github.com/intercom/intercom/pull/335428

Move Phone API back to development

---

descriptions/0/api.intercom.io.yaml
descriptions/2.10/api.intercom.io.yaml
descriptions/2.11/api.intercom.io.yaml
descriptions/2.7/api.intercom.io.yaml
descriptions/2.8/api.intercom.io.yaml
descriptions/2.9/api.intercom.io.yaml

toward https://github.com/intercom/intercom/pull/337832

Update search docs

---

descriptions/0/api.intercom.io.yaml
descriptions/2.10/api.intercom.io.yaml
descriptions/2.11/api.intercom.io.yaml
descriptions/2.7/api.intercom.io.yaml
descriptions/2.8/api.intercom.io.yaml
descriptions/2.9/api.intercom.io.yaml

toward https://github.com/intercom/intercom/pull/339003
- Removing `skip_notifications from versions 2.9, 2.10. and 2.11`
- Adding DELETE to Unstable version

Fix skip notifications and add delete tickets

---

descriptions/0/api.intercom.io.yaml

Part of https://github.com/intercom/intercom/pull/343237

Open-api specs for get ticket endpoint

---

descriptions/0/api.intercom.io.yaml

Part of https://github.com/intercom/intercom/pull/343544

Ticket type endpoint specs

---

descriptions/0/api.intercom.io.yaml

Part of https://github.com/intercom/intercom/pull/344244

Ticket update endpoint openapi specs

---

descriptions/0/api.intercom.io.yaml

Documentation update because of:
https://github.com/intercom/intercom/pull/344701

add custom states listing endpoint documentation

---

descriptions/0/api.intercom.io.yaml

Towards: https://github.com/intercom/intercom/issues/344952

update ticket states documentation

---

descriptions/0/api.intercom.io.yaml
descriptions/2.10/api.intercom.io.yaml
descriptions/2.11/api.intercom.io.yaml
descriptions/2.7/api.intercom.io.yaml
descriptions/2.8/api.intercom.io.yaml
descriptions/2.9/api.intercom.io.yaml

Towards: https://github.com/intercom/intercom/issues/264918

[Data Interop] update Search conversation Accepted Fields desc

---

descriptions/0/api.intercom.io.yaml

Add descriptions of `statistics.​assigned_team_first_response_time_by_team`, `statistics.​assigned_team_first_response_time_in_office_hours` and `statistics.​handling_time` to Unstable.
Towards https://github.com/intercom/intercom/issues/349610

Add conversation reponse time and handling time metrics to Unstable

---

descriptions/0/api.intercom.io.yaml

Documenting the undocumented ability to create Custom Object Associations via the Conversations Update API
Towards https://github.com/intercom/intercom/issues/368835#issuecomment-2536367681

Add documentation for creating Custom Object Associations on Conversations Update in Unstable

---

.github/workflows/generate_postman_collection.yml
.github/workflows/ts-sdk.yml

Towards: https://github.com/intercom/intercom/issues/374225

Bump setup-node action

---

descriptions/0/api.intercom.io.yaml
descriptions/2.12/api.intercom.io.yaml

Relevant changes: 
https://github.com/intercom/intercom/pull/382954
https://github.com/intercom/intercom/pull/383201

Add changes for new fields on create and update ticket endpoints

---

descriptions/0/api.intercom.io.yaml

Add details to indicate block contact will also archive their conversations

add more details to block contact

---

descriptions/0/api.intercom.io.yaml

Towards https://github.com/intercom/intercom/issues/379548
Add examples to Retrieve a Conversation endpoint

Add example to get conversations

---

descriptions/0/api.intercom.io.yaml

Towards: https://github.com/intercom/intercom/issues/384289

[TDF][Back Market Escalation] Document new attr in create_ticket_request (Unstable)

---

.npmrc
package.json

towards https://github.com/intercom/intercom/issues/385190

fix bugcrowd dependency confusion

---

descriptions/2.10/api.intercom.io.yaml
descriptions/2.12/api.intercom.io.yaml
descriptions/2.7/api.intercom.io.yaml
descriptions/2.8/api.intercom.io.yaml
descriptions/2.9/api.intercom.io.yaml

fixed paginated response schema link on conversations

fix conversation_list docs

---

descriptions/0/api.intercom.io.yaml

Towards https://github.com/intercom/intercom/issues/385933

Improve custom object instances docs & add delete by external_id endpoint

---

descriptions/0/api.intercom.io.yaml

Towards https://github.com/intercom/intercom/issues/385933

Update docs of associating CO with contacts

---

fern/generators.yml

one-liner to drop timeout to 20 seconds and surface the timeoutInSeconds attribute for clarity

drop timeout to 20s

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

Updated the template for PR descriptions like this
N/A

Update PR template

---

fern/generators.yml

Reverts intercom/Intercom-OpenAPI#284

Revert "Disable pr mode for sdk publishing to github"
